(test
 (name main)
 (modules main test_lwt_direct)
 (package lwt_direct)
 (build_if
  (>= %{ocaml_version} "5.0"))
 (libraries lwt_direct lwt.unix lwttester))

(test
 (name test_backtrace)
 (modules test_backtrace)
 (package lwt_direct)
 (build_if
  (>= %{ocaml_version} "5.0"))
 (libraries lwt_direct lwt.unix))
